### ISSUE TITLE
is_view undefined when calling eager_load!

### ISSUE THREAD

**Issue by thomassnielsen** [jasoncodes/activerecord_views#19] opened 2015-08-19 10:26 UTC
I'm testing out `activerecord_views` as an option for our new rails-based API backed by an existing database containing several views. We want to move db migration to ActiveRecord.

I've set up a model with a companion sql file containing the view, and removed the view from a db clone. When I try to run `Rails.application.eager_load!` in rails console, I get the following error:

```
NameError: undefined local variable or method `is_view' for #<Class:0x007fd67d499138>
```

My model `postalajax.rb` looks like this:

``` ruby
class Postalajax < ActiveRecord::Base
  is_view
end
```

My `postalajax.sql` looks like this:

``` sql
SELECT (postnums.num)::integer AS num,
  postnums.sted
  FROM postnums;
```

I've also verified that the gem is present in Gemfile.lock. Any suggestions for what might be wrong?

**Comment by jasoncodes** [comment] 2015-08-19 10:38
`is_view` should be defined as long as the railtie is loaded and invoked. This should normally happen automatically in a Rails app. I suspect the gem isn’t being required for some reason.

Is `activerecord_views` in the default Gemfile group?
Is the `gem 'activerecord_views'` line after `rails` (or `activerecord`, if specifying that directly)?
Does the `gem` line have anything like `require: false`?
Does `config/application.rb` have the standard `require "active_record/railtie"` and `Bundler.require(*Rails.groups)` lines?

**Comment by thomassnielsen** [comment] 2015-08-19 10:49
`require "active_record/railtie"` was missing. This is a recently generated project, and application.rb didn't contain that line when we generated the project. I tried to generate a new project just now to be sure, and `require "active_record/railtie"` is not a part of the default generation (anymore?).

Maybe it should be added to the instructions in `README.markdown`?

**Comment by jasoncodes** [comment] 2015-08-19 23:51
I just generated a fresh Rails 4.2.3 app, added `gem 'activerecord_views'` to the `Gemfile`, and created a new model file in `app/models` with `is_view`. `Rails.application.eager_load!` in `rails console` worked fine.

The generated `config/application.rb` does contain `require "active_record/railtie"`. Are you invoking `rails new` with any options and/or do you have a `~/.railsrc` file?

**Comment by thomassnielsen** [comment] 2015-08-20 09:31
I also generated a new app with rails 4.2.3, but mine does not contain `require "active_record/railtie"`. I do not have a `~/.railsrc` file. I just had my colleague do the same, and his looks like mine. The whole file looks like this:

```ruby
require File.expand_path('../boot', __FILE__)

require 'rails/all'

# Require the gems listed in Gemfile, including any gems
# you've limited to :test, :development, or :production.
Bundler.require(*Rails.groups)

module TestingDefaults
  class Application < Rails::Application
    # Settings in config/environments/* take precedence over those specified here.
    # Application configuration should go into files in config/initializers
    # -- all .rb files in that directory are automatically loaded.

    # Set Time.zone default to the specified zone and make Active Record auto-convert to this zone.
    # Run "rake -D time" for a list of tasks for finding time zone names. Default is UTC.
    # config.time_zone = 'Central Time (US & Canada)'

    # The default locale is :en and all translations from config/locales/*.rb,yml are auto loaded.
    # config.i18n.load_path += Dir[Rails.root.join('my', 'locales', '*.{rb,yml}').to_s]
    # config.i18n.default_locale = :de

    # Do not swallow errors in after_commit/after_rollback callbacks.
    config.active_record.raise_in_transactional_callbacks = true
  end
end
```

Versions:
```
~ ❯ ruby -v
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin14]
~ ❯ rails -v
Rails 4.2.3
```

**Comment by twe4ked** [comment] 2015-08-20 22:40
Just tried it here:

```
$ ruby -v
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]
$ rails -v
Rails 4.2.3
$ rails new foo
```

`foo/config/application.rb` doesn't mention `railtie`.

**Comment by jasoncodes** [comment] 2015-08-20 22:58
I do have a `~/.railsrc` file and it seems `--skip-test-unit` causes it to output individual `require` lines rather than requiring `rails/all`. Regardless, this doesn’t matter as `rails/all` includes each individual railtie. `activerecord_views` works fine. Not sure what the difference may be.

```
$ ruby -v
ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin14]
$ rails --version
Rails 4.2.3
$ rails new --no-rc --skip-bundle --database=postgresql foo
[…]
$ cd foo
$ echo "gem 'activerecord_views'" >> Gemfile
$ bundle
[…]
$ cat > app/models/bar.rb
class Bar < ActiveRecord::Base
  is_view 'SELECT 42 AS id'
end
^D
$ rails console
> Rails.application.eager_load!
[…]
> Bar.first.id
  Bar Load (0.2ms)  SELECT  "bars".* FROM "bars" LIMIT 1
=> 42
```

**Comment by thomassnielsen** [comment] 2015-08-21 08:42
That's even more strange, then, as my file had `rails/all`, but `activerecord_views` didn't work until I added `require "active_record/railtie"` specifically.

**Comment by jasoncodes** [comment] 2015-08-21 09:11
https://github.com/rails/rails/blob/v4.2.3/railties/lib/rails/all.rb is where the magic happens.

**Comment by jasoncodes** [comment] 2023-11-06 06:28
Closing this as unable to reproduce.

**Closed by jasoncodes** 2023-11-06 06:28 UTC
